{% set name = "apng" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apng-{{ version }}.tar.gz
  sha256: a3e4007fbadab2188ef80490bff4e75acc847158d22ec97176f6040ff76465ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - apng
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eight04/pyAPNG
  summary: A Python module to deal with APNG file.
  license: MIT
  license_file: LICENSE
  doc_url: https://pyapng.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - eight04
